--- 
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Copy file to remote system
      copy:
        src: /etc/ansible/template/named.conf
        dest: /mnt/
        owner: root
        group: root
        mode: 0640
